# remote_theme: raviriley/agency-jekyll-theme

# the base hostname & protocol for your site, e.g. http://example.com
url: "https://realbits-lab.github.io"

# the subpath of your site, e.g. /blog
baseurl: ""

title: REALBITS
#this is also the email contact forms will go to
email: dev.realbits@gmail.com
description: "About realbits"
author: realbits-lab
# logo:     #optional, defaults to site title
# path: assets\img\clients\creative-market.jpg
# height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
portfolio:

markdown: kramdown
# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/mknelrry"
